client.qc, player.qc, qw.qc, tfort.qc, tsoldier.qc, weapons.qc
Maybe medic will be a useful class with this change.
=> NG and SNG balance changes along with toggles

sentry.qc
Seemed to work fine in games on Sunday, can no longer reproduce bug
=> Sentry target fix

combat.qc, weapons.qc
setinfo hitsound 1 (enemy)
setinfo hitsound 2 (enemy + friendly)
sound/misc/
[hitsounds.zip](https://github.com/FortressOne/server-qwprogs/files/2849153/hitsounds.zip)
=> added hitsounds

actions.qc, client.qc, tfort.qc, weapons.qc
Make it able for the player to choose to use old weapon slots/impulses with "setinfo owi 1" or "setinfo old_weapon_impulses 1"
=> Old weapon impulses

admin.qc, client.qc, commands.qc, mvdsv.qc, quadmode.qc, qw.qc, status.qc
now when a user with adminpwd uses the "ceasefire" command, the server will pause the game.
when "ceasefire" is used again a countdown starts to unpause the game.
=> pause with countdown

client.qc, defs.h, qw.qc, tforthlp.qc, tsoldier.qc, weapons.qc
nginfo ingame to show a list of commands, havent really tested this much
=> Nailgren stuff

commands.qc
=> allowing admins to change map even with match in progress

mvdsv.qc
People were having trouble to unpause the game due to different pausedtic functions being used in mvdsv/ftesv
=> fixing pause for ftesv, keeping mvdsv compatibility

README.md, status.qc, tfortmap.qc
Optional.
setinfo sbflaginfo on
to enable.
Also updates some flag messages and coloured glows to cater for slightly more situations.
=> Flag messages and statusbar flaginfo

spect.qc, weapons.qc
Admin menu now works for spectators
=> fix for #113

spect.qc, weapons.qc
Fix rogue team select impulses on maps that don't support it
=> Team select

admin.qc, clan.qc, menu.qc, weapons.qc
Added ceasefire (and made it work with prematch/countdown too), ready status and forcestart to admin menu.
=> Admin menu

admin.qc, clan.qc, doors.qc, menu.qc, quadmode.qc, weapons.qc
Changed quad-round force close of doors to a silent function version
=> Quadround door sound looping

client.qc, qw.qc, tfortmap.qc
localinfo flagfollow / localinfo flag_follow to toggle flag model followind the player who has it.
Default: on
=> Flag follow toggle

README.md, status.qc
Fixed statusbar position jumping around sometimes. Fixed returned flags displaying location. Added option to override class tips with flag info after respawn.
=> Status Bar Flag Info fixes

client.qc, status.qc
Made the new, more generic function to get infokeys.
Changed statusbar to call the user-specific one.
=> Updated flagstatus to use new getuserinfo command

combat.qc
=> Building engineers and feigning spies get a death message now

engineer.qc
(and gets cells and a frag as a reward)
=> Issue #60: engineer now dismantles enemy buildings

client.qc
Works on versus and schtop at least
=> Supress generic kill messages when killed by a tf goal with a message

ssqc/client.qc, ssqc/qw.qc, ssqc/status.qc
Flag status is now seen on the hud icons instead
=> Don't show flag status on sbar if csqc is active

ssqc/tfortmap.qc
=> flag glow bug fix

ssqc/player.qc, ssqc/weapons.qc
=> fixes hwguy sometimes locked out of firing all weapons

ssqc/tfort.qc
I cannot recreate this bug on my local server, so we'll need to test on staging
=> fix as per spike for mvd recording

ssqc/q3.qc, ssqc/triggers.qc
=> Bouncepads

ssqc/commands.qc
- disallow changing to dodgy invincible class
- fix messages about already being the same class
=> fix changeteam limits and messages

ssqc/items.qc
#326 nail/shock gren pickup message fix
=> fix found nail/shock gren message

csqc/csextradefs.qc, csqc/events.qc, csqc/main.qc, csqc/menu.qc, share/defs.h, ssqc/csmenu.qc, ssqc/tforthlp.qc, ssqc/world.qc
instant csqc team -> class menus
=> instant csqc team/class menus

csqc/events.qc, csqc/input.qc, csqc/menu.qc
Trying to fix insta-menus for spy
=> fix spy special menu

README.md, csqc/hud.qc, csqc/main.qc
hud editing commands;
tracktarget spectator command
=> fo_hud_save and fo_hud commands for scripting

README.md, csqc/events.qc, csqc/main.qc, csqc/menu.qc, csqc/status.qc, ssqc/client.qc, ssqc/csmenu.qc, ssqc/qw.qc, ssqc/tforthlp.qc
Reverts FortressOne/server-qwprogs#382
=> Revert "Quadmode qol staging"

README.md, csqc/events.qc, csqc/main.qc, csqc/menu.qc, csqc/status.qc, ssqc/client.qc, ssqc/csmenu.qc, ssqc/qw.qc, ssqc/tforthlp.qc
=> Quadmode qol 3

ssqc/weapons.qc
=> fixing bug when selecting a weapon that you don't have - issue #403

README.md, ssqc/client.qc, ssqc/qw.qc
Just added a new "game mode" where you have to pick up your flag and capture it inside the enemy base
Basically it exchanges cap point and flag locations
Defaults to off
=> Reverse cap

ssqc/client.qc, ssqc/qw.qc, ssqc/status.qc
It's annoying and the huetf preset would need to be more scrutinised when used
=> fix csqc flagstatusinit on map change

ssqc/commands.qc, ssqc/functions.qc, ssqc/menu.qc
=> replace \[ with \x10 and 11

ssqc/client.qc, ssqc/commands.qc, ssqc/functions.qc, ssqc/login.qc, ssqc/quadmode.qc
a number of login-related fixes for bugs that are impacting our stats generation
=> a number of login related fixes

ssqc/admin.qc, ssqc/clan.qc, ssqc/client.qc, ssqc/events.qc, ssqc/functions.qc, ssqc/quadmode.qc, ssqc/qw.qc
running this for a while now, no gameplay changes
=> Invalid player events double demo fix

ssqc/admin.qc, ssqc/clan.qc, ssqc/client.qc, ssqc/combat.qc, ssqc/events.qc, ssqc/functions.qc, ssqc/quadmode.qc, ssqc/qw.qc
Pyro was able to throw hwguys around with his rocket because it wasnt going through its momentum reduction as every other explosive damage
=> Pyro oztf moment fix

ssqc/client.qc, ssqc/commands.qc, ssqc/functions.qc, ssqc/qw.qc, ssqc/spect.qc, ssqc/vote.qc, ssqc/world.qc
=> Spec teamscore

ssqc/antilag.qc, ssqc/engineer.qc, ssqc/hwguy.qc, ssqc/pyro.qc, ssqc/spy.qc, ssqc/weapons.qc
HWGuy entities do not move in a 'forward' direction. This leads to slightly strange behaviour with regards to bullet spread. Fix this.
=> Project ents using their velocity

ssqc/weapons.qc
=> Fix assault cannon not responding to reloadnext

share/defs.h, ssqc/client.qc, ssqc/player.qc, ssqc/qw.qc, ssqc/spy.qc, ssqc/weapons.qc
=> Insta knife

csqc/csextradefs.qc, csqc/main.qc, csqc/status.qc, share/defs.h, ssqc/clan.qc, ssqc/client.qc, ssqc/qw.qc, ssqc/weapons.qc, ssqc/world.qc
=> Let people know when they're last to ready up

csqc/main.qc
=> Separate updateview

ssqc/client.qc, ssqc/combat.qc, ssqc/menu.qc, ssqc/qw.qc, ssqc/spy.qc, ssqc/tfort.qc, ssqc/weapons.qc
Introduces localinfo feign_rate_limit [default=5s] which controls how frequently you can spam feign.
Removes duplicate code of assumed equal functionality.
=> Feign spam

csqc/csextradefs.qc, csqc/main.qc, csqc/status.qc
You can revert the other merge and replace it with this updated one
=> FTE / CSQC rendering performance fixes

README.md, ssqc/qw.qc, ssqc/tfort.qc
=> Merge precise grenades to master

ssqc/login.qc
Misread prior error message, this is just a proto change and still being used by some communities.
=> Restore URI_GetCallback

ssqc/antilag.qc
Temporarily revert to the basic seek and fix a misclamp on rtt.
=> Saw a mismatch between the optimized and basic seek i testing.

README.md, share/defs.h, ssqc/actions.qc, ssqc/antilag.qc, ssqc/client.qc, ssqc/commands.qc, ssqc/engineer.qc, ssqc/menu.qc, ssqc/progs.src, ssqc/qw.qc, ssqc/spy.qc, ssqc/tfort.qc, ssqc/tfortmap.qc, ssqc/weapons.qc
Unifies ping correction and introduces a bunch of new corrections (e.g. time to fire, feign, build).
Rewrites reload in preparation for client side animation/weapon prediction.
=> Unified ping correction on all the things, reworked reload for weapon prediction

share/fo_weapons.qc
Helps if you git add new files.
=> Add new files

share/defs.h, share/fo_weapons.qc
There are a few cases where there's no weapon (e.g. setting detpack) add WEAP_NONE to handle this properly.
=> Add WEAP_NONE

ssqc/player.qc
Moved an offset in prior commit, was skipping spindown sound on first frame
=> Fix spin-down sound

ssqc/antilag.qc
Other changes in staging (proto from another file we pick up) were providing this for higher functions in the file.
=> Move up prototype for CF_GetSetting

share/fo_weapons.qc, ssqc/weapons.qc
Also extend handling to default_weapon which I'm not sure was covered before (although not commonly used).
=> Make sure we swap pyro 1/2 slots with cf_pyro_impulses

ssqc/weapons.qc
This is a little annoying since we're trying to walk [1234/4321] but with CFPI we must also consider [2134]/[4312].
=> Also handle CFPI with weapnext/weapprev

csqc/weapon_predict.qc, share/animate.qc, share/weapons.qc, ssqc/weapons.qc
Fix hwguy slow speed after firing (bits from next patch series leaked) Fix demoman not being able to fire after setting detpack while reloading
(note, client side weaponmodel is showing up on the latter case still, but you can't actually fire.  Will fix this properly by moving it into tfstate.)
=> Fix hwguy/demoman buglets

ssqc/weapons.qc
A null check was inverted on the last commit, blocking some operations
=> Fix inverted slot check

csqc/weapon_predict.qc
Zero seems to be correct.  No docs.
=> Seat != playernum

csqc/weapon_predict.qc
Most of the core working well, but some details to handle (more cvar support and quick switch in particular)
=> Temporarily put things behind a flag

csqc/weapon_predict.qc, share/weapons.qc, ssqc/weapons.qc
Implement CSQC handling of these as well as the warts around old weapon impulses and swapped pyro impulses.
=> Clientside WEAPPREV/WEAPNEXT

csqc/hud.qc
=> Fix fo_hud cmd

ssqc/weapons.qc
Search and replace missed a spot.
=> Fix NG/SNG not hitting

csqc/input.qc
=> Remove debug prints

csqc/weapon_predict.qc, share/weapons.qc, ssqc/events.qc
I suspect it's the logging code, but extra catches added just in case.
=> Track down OOB

ssqc/pyro.qc, ssqc/tfort.qc
- Make airblast work again (it was working before, but not updating local physics)
- Make napalms/shock/gas not freeze when they reach expiry (part of more precise explosion locations for other types)
- Minor clean-up to napalm code
=> Physics updates

csqc/events.qc
fo_hitaudio_* cvars should work now
=> hitaudio cvar fix

csqc/csextradefs.qc, csqc/menu.qc, csqc/status.qc
- Refactor scoreboard to simplify/remove some repetition, small performance improvements
- Better truncation handling for coloured names
- Cache on startup whether or not we have icons for ready/chat/afk
=> scoreboard: refactor

csqc/status.qc
array for teams list was off-by-1
=> scoreboard: fix array length

csqc/csextradefs.qc, csqc/status.qc
render the background of the currently spectated player (if any) in yellow
=> hud: highlight spectated player on scoreboard

csqc/weapon_predict.qc
Saw some negative feedback on the last implementation.
=> minping: update convergence loop

ssqc/world.qc
=> bodyqueue: remove debug prints

ssqc/qw.qc, ssqc/status.qc
foca -- base amplitude [default 100]
focs -- scout multiplier [default 1.5]
focs -- medic multiplier (when affected) [default 0.5] foch -- heavy multiplier [default 0.75]
=> experimental: make some cuss parameters tunable

csqc/main.qc
blending was linear vs intended curve, try to reduce motion blur from viewport changes
=> experimental: conc reduce blur and fix blend curve

csqc/weapon_predict.qc, ssqc/status.qc, ssqc/tfortmap.qc
- print your head is better message
- make sure effect is removed on cap
- make it a little less brutal for heavy by default
- clean up some stuff that allows live edits
=> experimental: cleanup conc

csqc/main.qc
=> experimental: make sure new cuss doesn't bleed through

csqc/main.qc, csqc/weapon_predict.qc
- v_forward was getting reversed
- lower conc-render fps to reduce blur
- fix clown conc
=> experimental: minor fixes

share/animate.qc
Just say no to heavy buffs.
This reverts commit 86f76c6318e36917950395198b2904e971428cdf.
=> Revert "Temp fix for heavy cannon skipping as hpb"

csqc/main.qc
Put a bound on view bob beyond it just being a reduced function of amplitude so that scout is a little more controllable / less nauseating.
=> experimental: bound view bob

share/animate.qc
CSQC side was filling in wrong field
=> hwguy: fix locked weaponframe selection

csqc/csextradefs.qc, csqc/events.qc, csqc/main.qc, csqc/status.qc, csqc/weapon_predict.qc
No reason that I can tell for them to be separate and simplifies the code.
=> csqc: unify is_player and is_observer

share/weapons.qc
Classic impulses were off by 1 after refactoring.
=> slots: fix off by 1

share/prediction.qc
=> pm: bound number of filter ents

ssqc/tfort.qc
(4 too aggressive for first move)
=> teamplay: just kidding, 5 seconds delay

ssqc/client.qc, ssqc/scout.qc, ssqc/teamplay.qc
1. Med Cuss cap being applied to OCE Only
2. Med Cuss duration of 2 seconds removed
3. effstrip enemy ammo on capture disabled
=> Fix new_balance med and capture flag 

docs/versions.txt
Changing any references of "goal_results" to "goal_result". This resolves issue #696.
=> Correct goal_results to goal_result
