admin.qc, clan.qc, client.qc, commands.qc, defs.h, mvdsv.qc, player.qc, progs.src, quadmode.qc, qw.qc, spy.qc, tfort.qc, tforthlp.qc, tfortmap.qc, weapons.qc, world.qc
**Changes**
No more prematch time limit, prematch will go on until everyone is ready or admin forces a match start.
Clock should be in sync when match actually starts (tested with the original ezquake client)
**For players:**
_/ready_ - makes you ready to start
_/notready_ (or _/ready_ again) - makes you not ready anymore
**For admins:**
_/clan_ - sets up clan mode, you have to restart the map
_/quadmode_ - same, but for quad mode
_/startmatch_ - forces the match to start, ignoring if players are ready or not. The same behaviour will happen if _/ceasefire_ is used twice.
_/readystatus_ - broadcasts a list of players who are not ready
**Quadmode:**
Right now it's following brazilian ruleset, we may change it and make it configurable.
Two rounds of 10 minutes with a short intermission in …
=> Quadmode and ajustments to Clan Mode

tfortmap.qc
Spoike: conceptually its goal is to set .model (and thus also needs to set .modelindex otherwise the client won't see the change), it MAY also change mins/maxs (although what it changes it to is always annoying), it then relinks the entity (which sets .size, and the exact results also depend upon .solid)
[19:24] Spoike: if its 'until player-specific-change', then the bug itself is not in the setmodel builtin.
[19:26] Spoike: whether setmodel changes mins/maxs depends upon the game. for quakeworld, it'll do it ONLY if the extension is .bsp (dedicated servers don't load mdls, and don't try according to the file extension in setmodel)
[19:28] Spoike: (vanilla netquake doesn't check extensions, but will always use +/- 16 for the size - a fact that also breaks culling, which means that many nq …
=> the setsize call seems to help

client.qc, qw.qc, weapons.qc
Toggle 'localinfo cwaf' to change behaviour, default remains the previous one (with delay)
fixes #104
=> adding a toggle to prevent weapon change delay

qw.qc, status.qc, tfortmap.qc
StatusBar FlagInfo changes:
- For maps with 3 teams or less, uses 2 lines to report flag status and location
- Location is only displayed after a second or so of being dropped, allowing the flag to be passed around secretly
- For info_tfgoals with track_goal set to 1, will display additional countdown if they're in their delayed state. netname must be set, team_str_moved can optionally be used as the "offilne" status string.
It will only appear if there's room in the status bar and disappear once the countdown has finished.
- Flagdrop message fix (was throwing errors in server console).
=> Statusbar flaginfo location

client.qc
This commit fixes a bug known for us as "anti-fell", that allows users to take no fall damage due to cl_c2spps command issued in air and +jump before reaching ground. This fix is compatible only with FTESV as it depends on SV_RunClientCommand.
Another way to fix this for MVDSV could be to modify MVDSV to call SV_PostRunCmd after each SV_RunCmd in SV_ExecuteClientMove @ sv_user.c.
=> Fix: Anti Anti-Fall Damage

csqc/hud.qc
=> split the identify string up so it prints better via csqc

ssqc/status.qc
=> Fix double 'clip:' on legacy statusbar

csqc/csextradefs.qc, csqc/events.qc, csqc/main.qc, csqc/settings.qc, menu/options_basic.qc, ssqc/tfort.qc
So now the server-side grentimer is still controlled by `setinfo nt 0/1` and client-side by the `fo_grentimer 0/1` command. Might still need to review this for use with the menu though.
=> Hud more options

ssqc/commands.qc, ssqc/tfort.qc
internally, classes seem to be limited to the current number of players on the team, so switching soldier -> demo -> soldier before dying would come up as restricted as it would estimate 2 future soldiers (current class + target class) for only 1 team member. Exclude check now.
=> even better class change logic

ssqc/client.qc, ssqc/commands.qc, ssqc/qw.qc, ssqc/tfort.qc
Created a preset for HueTF rules, so we can move away from setting localinfos via cfg files.
Also moved round_delay_time away from "quadmode" command due to inconsistencies (eg: we set round_delay_time to 10 on server config files, however when someone activates quadmode by hand it gets reset)
=> creating huetf preset, moving round_delay_time from quadmode to default

ssqc/tfort.qc
This PR addresses #515 which allows the user to set `setinfo ec on` or `setinfo ec 1` to execute class configs, and `setinfo em on` or `setinfo em 1` to execute map configs.
=> Allow "on" value for setinfo ec as well

ssqc/actions.qc, ssqc/weapons.qc
Add MOVE_LAGGED to weapon traces so hitscan weapons can be antilagged with sv_antilag 1 without also enabling antilag for projectiles
=> Add MOVE_LAGGED to weapon traces

ssqc/client.qc, ssqc/qw.qc, ssqc/scout.qc, ssqc/tfort.qc
Add support for cuss duration based on distance from explosion. 
Intended for use with medicnocuss = OFF, and cussgrentime = 15 (or higher than 10 as it currently is). TBC.
Rationale: 
- rewards accurate cuss throws when used offensively
- makes user have to choose between moving enemies out of the way or disabling them
- rewards good timing when used for mobility, and makes cuss jumping viable again for scout
=> Add distance based cuss duration option

csqc/events.qc
Matching on player_localentnum is too broad since we assume the identity of other ents when spectating obseriving.  Filter these cases out.
It's possible we need isdemo() also; but at least the demos I tried worked.
=> Fix missing jump sounds

ssqc/actions.qc
Discard turns out to have a user triggerable DOS where we always create the entity, even if there is nothing to discard.  Spamming this you can fairly quickly crash a server by exhausting progs VM memory (32mb).
=> Fix discard DOS

ssqc/client.qc, ssqc/combat.qc, ssqc/menu.qc, ssqc/qw.qc, ssqc/spy.qc, ssqc/tfort.qc, ssqc/weapons.qc
Introduces a rate limit, set by localinfo feign_rate_limit [default=5s] which bounds how frequently you can manually feign.
Feigning in reaction to damage ignores this limit (e.g. you can manually feign, unfeign, take damage, and refeign), but it will still count towards your next manual feign.
Also, delete duplicate CF implementation of Feign.  Both implementations were previously being used.  If this breaks anything we'll have to figure out how they're different.
=> Rate-limit feign and remove dead code

README.md, ssqc/qw.qc, ssqc/tfort.qc
Up to this point, all version of Team Fortress (including FortressOne)
have implemented grenade throwing using a test which executes every
100ms.  This introduces a random input-delay (of up to 100ms) dependent
on when you press throw relative to the next timer evaluation.
This introduces a new, 'precise' timing mode that throws grenades
immediately when instructed.
We reserve the final 100ms before the grenade explodes.  Previously, it
was random whether or not you would be able to throw in this time.  Now
it is deterministic, if you hold a grenade to this point, you are along
for the ride.  This is to allow future client-side prediction on
knockback to function reliably (as this allows us to predict the grenade
explosion position from player position when held more reliably).
Note that …
=> Implement precise grenade throwing

csqc/csextradefs.qc, csqc/events.qc, ssqc/status.qc
For CSQC enabled clients we synchronize the grenade timer with the server's notion of when the grenade was actually primed to eliminate ping dependency.
There's a bug in the current synchronization in that it offsets the predicted time by a full RTT, when the server starts the time when it receives the message, e.g. ~RTT/2.  This means that the timer has still been off by half-ping, better, but not perfect.
We correct this, but introduce a replacement implementation: the server additionally sends exactly what time it thinks the grenade was primed, so that we do not have to approximate it around ping.
We maintain the value of "fo_grentimer == 2" to mean, server assisted grenade timers, but default it to the new implementation.
We leave a temporary legacy fo_grentimer==3, which can be used …
=> Improve grenade timers

ssqc/pyro.qc, ssqc/quadmode.qc, ssqc/qw.qc, ssqc/spy.qc, ssqc/tfort.qc, ssqc/weapons.qc
A long standing bug is that napalm grenades occasionally do not explode properly, leaving glowing, stuck entities.
This turns out to be a race between several pieces of the code.
1. When the grenade initially explodes render a flare and start a timer program for the subsequent napalm explosions ("grentimer").
2. When the program in (1) begins 100ms later, it tries to track the number of napalm (or gas) grenades active for the player in question.
3. When the player dies, conditional on there being no active napalm grenades we try to reclaim these timers.
It turns out that when (3) occurs between the 100ms between (1) and (2) that the accounting can be incorrect and we'll remove the timer, but this incorrectly eliminated the subsequent explosion and left the grenade pinned until the ent was …
=> Fix not-exploding napalm grenades (and eliminate grentimer effects)

csqc/menu.qc
Menus were still using thisorigin, ensure it's set when active.
=> Fix context menus

README.md, csqc/csextradefs.qc, csqc/events.qc, csqc/hud_helpers.qc, csqc/main.qc, csqc/status.qc, share/defs.h, ssqc/antilag.qc, ssqc/client.qc, ssqc/qw.qc, ssqc/status.qc, ssqc/tfort.qc, ssqc/weapons.qc
Due to their prime-wait-throw nature, grenades have all sorts of
inconsistencies introduced by delay between client and server around
each event.  E.g. The player's idea of when they are priming and throwing
does not match up with the server's.
Two players that see each other at the same time, and prime at the same
time, will actually not be able to throw at the same time as the
player with the lower ping is able to get the server to register their
prime first.
This is particularly material since grenades don't allow you to throw
for the first 800ms, so even 50-100ms ping differences are a large
relative advantage.
This introduces ping correction, so that the point at which we consider
the client to have primed is corrected for their latency when enabled.
We ensure that this does not let …
=> Grenade ping correction

csqc/events.qc, share/defs.h
So a major part of the issue seems to be that the reference "self" was changing due to migration of timers into a class.  However, it turns out we were getting fortunate before and that self was actually the world entity and not the player.  This turns out to be the entire reason that soundupdate even worked with localsound, as the latter implies a default entity of zero.  This explains why we got double sounds even with the identical calls under the new code (as implicit entities from the grentimer entities were substituted.
This seems to work, I get very occasional misses, but I suspect those were the ones you were also seeing before.
I'm not sure about the PHS stuff, I've gone through the FTE code and it doesn't look like it's strongly interpreted for Q1 despite the docs and other …
=> The hunt continues.

csqc/csextradefs.qc, csqc/events.qc
own channels and get out of the channel game entirely.  Seems to work reliably under testing.
Also try to "perfectly" emulate the old grenade timer sounds in case there are still problems.  This means pulling them out of the object and back to the CSQC-call chain so that self can be world and not the object.  This can be enabled with fo_grentimer_debug 2.
(I tried it the other way but under testing the new timers seemed more reliable now that they're on their own ent (from sound system pov) so..... we'll see.)
=> Assign ent numbers to grenade timer objects so that we can play on their

csqc/csextradefs.qc, csqc/events.qc, share/defs.h
Flip default to old timers so we don't pick up grentimer_debug into clients for testing.
In effort to mirror original magically working state (which is the default), restore original channels.
Fix caching which got dropped in merge.
Small cleanups.
=> More tweaks for grentimer reliability

README.md, ssqc/tfort.qc
Now that we're happy with the new behavior and there's no differences from the old beyond precision, eliminate the old code and precise grenade option, there are now only "FO Grenades".
=> Remove "non-precise" grenades

csqc/csextradefs.qc, csqc/status.qc
zel pointed out it's nicer to stack timers by expiry time when some is spamm^Whas several active simultaneously.
Also, he thought he might have seen 2 opaque timers.  This could happen momentarily if prime and throw messages are reordered, but we can actually hide this easily by always rendering stacked timers as transparent.
=> Grenade timer visual tweaks

ssqc/client.qc, ssqc/qw.qc, ssqc/vote.qc
The voting code is fairly spaghettified; but this adapts the existing (partial) clanbattle disable and makes sure we also hit the entry points that I found in commands.qc
=> Disable voting in quadmode

ssqc/pyro.qc, ssqc/quadmode.qc, ssqc/qw.qc, ssqc/spy.qc, ssqc/tfort.qc, ssqc/weapons.qc
A long standing bug is that napalm grenades occasionally do not explode properly, leaving glowing, stuck entities.
This turns out to be a race between several pieces of the code.
1. When the grenade initially explodes render a flare and start a timer program for the subsequent napalm explosions ("grentimer").
2. When the program in (1) begins 100ms later, it tries to track the number of napalm (or gas) grenades active for the player in question.
3. When the player dies, conditional on there being no active napalm grenades we try to reclaim these timers.
It turns out that when (3) occurs between the 100ms between (1) and (2) that the accounting can be incorrect and we'll remove the timer, but this incorrectly eliminated the subsequent explosion and left the grenade pinned until the ent was …
=> Fix not-exploding napalm grenades

ssqc/antilag.qc
Enable antilag detpipe by default and move rendering rewind pointsbehind `rewind_debug_show`.
=> Enable antilag detpipe by default 

ssqc/clan.qc
This doesn't update fast enough when clients crash and is causing problems where people can't rejoin running games quickly enough.  (More than the disruption random players were causing, which we can at least password away.)
=> Default the player quad limit to off for now

share/fo_weapons.qc
When filling in the switch table for all the weapons a few breaks were missed at the end.  This was resulting in (for example) grenade launcher not needing reload.
=> Add missing breaks (fix no reload on grenade launcher)

ssqc/clan.qc
This is locking players out with password set, while there are known interactions with 'reconnect', this also seems to include 'disconnect;password;connect'.
Only way to rejoin has been to clear the password.  Remove for now.
=> Disable auto-assword quad code.

ssqc/hwguy.qc, ssqc/weapons.qc
A few weapons implement attacks via the animation code, namely the assault cannon, and both nailguns.  While this had no interaction with the nailguns, as their own animation code was setting the same attack_finished values, this was causing problems with the assault cannon that uses out of band synchronization around spin-up/spin-down.
For completeness, exclude all 3 from setting attack-finished.  At some point nailguns can probably have it pulled out of the animation code but that's a question for another day (might matter for NG more than SNG).
=> Fix attack_finished nits

share/fo_weapons.qc, ssqc/client.qc, ssqc/player.qc, ssqc/tfort.qc, ssqc/weapons.qc
- Autorifle wasn't on the right slot for sniper
- NG/SNG had bugs in both new and old code with attack finished interactions on running out of ammo (in the old code the animation would keep generating muzzle flashes, in the new code it would stop firing but not switch).  Now properly works.
- There was a ton of spaghetti in the old hwguy cannon implementation, missing weapon switches on certain ammo cases, duplication across multiple animation functions.  Not all of this seemed to be working right so just rip it all out and rewrite it.  Seems good now.
=> Fix weapon nits

csqc/events.qc
Last step before deleting the old code and merging to master, everything seems to be working well for people now.
Also confirmed that there was an FTE use-after-free bug in reading the grenade timer sound from cvar that was occasionally resulting in crashes.  That bug is being fixed FTE side and our migration to auto-cvar in the meanwhile is sufficient to fix on ourside.  This fixes client hitches so let's make sure everyone gets it again.
=> Roll everyone over to the new timer implementation by default

share/fo_weapons.qc
We've seen a single crash on an OOB array of size 4, this is the obvious candidate.
=> OOB slot check

ssqc/antilag.qc, ssqc/qw.qc
It turns out the undefined optional behavior dominates default parameter, so:
foo(optional int param = 1)
Will be invoked with param = <random> and not 1.  This was disabling antilag by selecting an undefined mode with a max of 0.
=> Re-enable antilag

ssqc/weapons.qc
We still support the old impulses when `old_weapon_impulses` is set, but the filtering was too aggressive (<=1 vs <1, same for 7).
=> Fix impulse 1/7

ssqc/client.qc, ssqc/weapons.qc
In adjusting attack_finished for ping we need to make this on both sides, e.g. when the client fires and when we subsequently check.  In missing the second we'd allow firing rate to increase with latency.  Also re-add catch-all that was previosuly present for no ammo and minor cleanup.
=> Ensure ping correction can't affect firing rate

share/fo_weapons.qc, ssqc/player.qc, ssqc/weapons.qc
The prior approach failed to account for the fact that some of weapon animations have attack_finished embedded in them, resulting in overlapping calls.  This was pushing the finished time out unreasonably.
Just remove the max for now, we're going to make some other changes that will smooth out client_time in the face of jitter anyway.
=> Tie attack_finished to client_time() for now

csqc/csextradefs.qc, csqc/events.qc, share/commondefs.qc, ssqc/admin.qc, ssqc/mvdsv.qc
It's rather frustrating that ceasefire causes all the active grenade
timers to lose sync (the visual timer pauses, but the sound just keeps
playing).  Implement actual pause/unpause of the timer sound around
ceasefire start/end.
=> Sync grenade timers with cease fire

share/fo_weapons.qc
Generically called from impulse commands, could be no weapon.
=> Make sure ReloadSlot checks for not a nullslot

ssqc/admin.qc
Deceptively works with a list length of 1 for testing before.
=> Fix runaway loop in ceasefire grentimer restart

ssqc/client.qc
This was intended as a conservative state reset but it triggers other last selected weapon logic later and results in always spawning with axe, Null's a more correct choice anyway.
=> Spawn with SlotNull not Melee

share/fo_weapons.qc, ssqc/client.qc
A missing comma was resulting in silent string concatenation and a table size of
4.  This was leading to OOB references that looked like they were on slots but were really on ammo.
Originally I was going to restore grenades as an ammo type here (with flavour text) as well but other stuff is yielding a message first so will look at that later.
=> Fix Ammo table

csqc/main.qc, csqc/weapon_predict.qc, share/animate.qc, share/defs.h, share/weapon_predict.qc, ssqc/pyro.qc
- Speed up animation convergence time
- Defer animation start to line up with remote fire
- Tweak how we match start of firing for cleaner animations
- Nails are now predicted nicely
- Add csqc debug dump
- Previously full refresh could miss zero fields that had been lost due to packet drops, fixed.
- Pyro rockets now matched up with server side
=> Projection refinements

csqc/weapon_predict.qc, share/weapon_predict.qc
It needs its own type because projectile is a different model.
=> Re-enable projectile matching for SNG

share/animate.qc, share/defs.h, share/weapon_predict.qc, share/weapons.qc, ssqc/admin.qc, ssqc/client.qc, ssqc/demoman.qc, ssqc/engineer.qc, ssqc/hwguy.qc, ssqc/player.qc, ssqc/qw.qc, ssqc/scout.qc, ssqc/sniper.qc, ssqc/spy.qc, ssqc/tfort.qc, ssqc/weapons.qc
- Introduce TFSTATE_NO_WEAPON to handle cases where firing is disabled (e.g. detpack, feign, etc).  This both standardizes behaviors and allows prediction sync.
- Migrate TFSTATE flags to enumflags, remove a bunch of stale ones
- Move speed synchronization into Think (triggered off changes in tfstate) rather than trying to make SetSpeeds.
- Fix a bug where heavy could fire too fast while moving.
- Fix several bug with feign (new and old)
=> Big tfstate cleanup

ssqc/client.qc
The update function handled reload, the wrapper wasn't watching for it.
=> Fix weapon model showing during reload

csqc/weapon_predict.qc
Originally was separating this but it's behaving fairly well with latest updates and turns out to actually matter for projectiles (since otherwise you can change weapons fast enough that client still thinks you are using previous weapon and creates incorrect predicted projectiles).
Could possibly separate tracking and rendering in the future but goal is to just make this unnecessary and always automatically on.
=> Turn on weapon prediction by default

csqc/events.qc, csqc/weapon_predict.qc, share/defs.h, share/prediction.qc, ssqc/client.qc, ssqc/engineer.qc, ssqc/pyro.qc, ssqc/scout.qc, ssqc/weapons.qc, ssqc/world.qc
Add client-side sound for all predicted weapons, match up with animations, and conditionally filter server sounds whenever prediction occurred.  Also, substitute sound later when we realize prediction was missed.
=> Match client-side sound with animation

csqc/main.qc, csqc/weapon_predict.qc
Projectile prediction depends on weapon prediction to know when to generate the projectile (including cases such as being blocked out by reload, what the correct projectile is, etc).
Simplify enable state by making this dependence more clear, eliminating some code where we briefly considered supporting PP without WP.
=> Simplify WP/PP Enabled

share/prediction.qc
modelindex can be manipulated independently of model
=> Make sure projectiles appear on legacy clients

csqc/profile.qc
Disable profiling by default, now controlled by fo_enable_profiling 0/1
=> Making profiling togglable

csqc/hud_helpers.qc
Null skip was comparing address of local pointer, also add explicit !HUDP_INVALID check on id.
=> Fix handling of legacy/invalid panels

ssqc/antilag.qc
Cutting out antilag projection was intentional, but this now also cuts out newmis forwarding.  Restore.
=> Make sure we still static project with LAN pings

csqc/csextradefs.qc, csqc/hud.qc, csqc/input.qc, csqc/main.qc, csqc/menu.qc, csqc/sui_sys.qc
We were able to process escape twice from the same input leading to the menu simultaneously closing and opening.  While here, clean up some legacy code such as MouseDown and a double new-frame check.
=> Fix Escape on Menus

csqc/weapon_predict.qc, share/prediction.qc
This got wrapped the wrong way (ifdef SSQC) while splitting up patches.  Update and move it to static nudge.  Also, we don't need to transmit angles for our projectiles, it can be derived from velocity.
=> Fix physics frame nudge to be client-side & optimize netcode

csqc/weapon_predict.qc, ssqc/tfort.qc
Crash before was likely a held grenade which gets spawned as a child of the originally held grenade and wasn't copying the type over.
=> Add more gren_type annotation

share/physics.qc
And make unsupported movetypes non-fatal so we can back out qcp without restarting server.
=> Support MOVETYPE_NONE

share/physics.qc
Restore old behavior which ignored the plane normal and let you stick grenades (e.g. pipes) on slopes more easily.
=> Don't bounce down slopes by default

csqc/input.qc
Build menu was capturing mouse inputs so you couldn't swing wrench once open.
=> Fix build menu stopping swings

csqc/weapon_predict.qc, share/physics.qc, share/prediction.qc
Radius searches on explosion need the earlier setorigin it seems.
=> Restore setorigin and skip void ents

csqc/csextradefs.qc, csqc/main.qc, csqc/status.qc, share/defs.h, ssqc/world.qc
Velocity was embedded into a stat field for speed display on the HUD.  This is a non-optimal choice both because it changes incredibly quickly and a better (more up-to-date) copy is already available client side in the form of pmove.
Reduces BW used from ~60k/s to 45k/s.  Should also likely help with proxy overflows.
=> Reduce bandwidth used by ~25%

csqc/weapon_predict.qc, share/commondefs.qc, ssqc/spy.qc
Delayed entity removal was allowing for multiple touches dependent on ping, angle, and newmis.  But keep a clown mode that allows it.
=> Fix Instakill Tranqs

csqc/weapon_predict.qc, ssqc/tsoldier.qc
We're seeing the occasional disconnect where a projectile is missing its type. But this should always be sent; seems to happen to HPBs.  One guess is maybe the original packet is being lost on a shock grenade and then flags is being smashed by the movetype update?  Ensure this doesn't happen by ORing (and make sure we actually pass back the movetype -- didn't matter since no vel).
In the meantime, prevent it from crashing by giving it a (intentionally probably wrong) model.
=> Augment, don't override flags when popping up shock grenades

ssqc/rewind.qc, ssqc/time.qc
Just in case entity was already rewound to another point in time.  Make sure that update spam can't drag an entry forwards indefinitely.  Ensure last-update is aligned with log record.
=> Use held origin when we need a now rewind point

csqc/weapon_predict.qc, share/prediction.qc
Remove and simplify some legacy bits from bringing up the new physics code.  Now that grenades have their own independent rewind timing/enable (due to a bunch of properties specific to them), key on that for whether to generate a client side projectile (if not enabled, there's no rewind to project against).
=> Simplify predict decision for handgrenades

csqc/main.qc, csqc/weapon_predict.qc, share/commondefs.qc, share/prediction.qc, ssqc/tfort.qc, ssqc/tsoldier.qc
Add Support for synchronizing clients to an automatic minping.
Configured via `localinfo min_ping_ms x` (or mpm for short).  Cooperating clients will automatically calibrate their delay-packets in a uniform fashion.
=> Automatic minping

csqc/main.qc, csqc/pmove.qc, csqc/weapon_predict.qc
We can't recover prior pmove vals from getinputstate so until we're running pmove, just snoop the trailing edge of clientcommandframe.
=> Run jump prediction of leading client frame for now

csqc/csextradefs.qc, csqc/events.qc, csqc/main.qc, csqc/pmove.qc, csqc/settings.qc
This was generating compilable, but not correct code that would end up using FOCMD_... for cvar definitions.  This was further masked by an incorrect use of cvar() sneaking back into the code that allowed it to pick up the legacy value on a client that had previously defined it (although it would be missing on a new install).
While we're here, shoot another cvar() that's crept in around fov.
=> Fix autocvars around prior FOCMD defines

csqc/pmove.qc
We need this in pmove, but while we're building the input frame we have to omit or we'll clobber the in-situ frame.
=> Don't pull inputs in inputframe

csqc/main.qc, csqc/pmove.qc
Some versions of FTE do not correctly update pmove_vel (although other state, e.g. pmove_org is).  Until we're directly tied to pmove, we snoop on recent values when we think this is happening.
This seems to be fixed on newer builds.
=> Workaround FTE pmove_vel bug

csqc/weapon_predict.qc, share/prediction.qc
Eliminate 2 sources of mismatch between client and server animation:
1) Turns out to be a general fix, readshort is signed (and writeshort will just pass through unsigned) and we were clipping the range on our base.  Leading to client and server using different prng bases for some value.
2) It's possible also to just mispredict/miss/etc.  We can filter these out by having the server animation follow the client's choice in the case we got it wrong.
=> Better matching of melee animations

csqc/weapon_predict.qc
- Make sure we only frame match on melee slots (external animation frames are unique, weapon model frames aren ot)
- Make sure we don't emit projectiles for not-in-animation cases when we have no ammo.
=> Animation tweaks

csqc/status.qc
It turns out this only ever worked by luck before (happening to get the right trash on stack).  Flickering was due to inconsistent trash on stack.
=> Fix scoreboard flickering

share/animate.qc
The starting weapon-frame is variable depending on whether the a, or b, swing animation is being used.  This could result in the multi-frame hit counter not being reset on b-swings after a-swings.  Use thinkindex() instead which is uniform across the two animations.
=> Use thinkindex to reset hit_in_current_animation

csqc/weapon_predict.qc, ssqc/weapons.qc
mashing +slot on top of +slot creates confusion since we couldn't actually process the prior weapon change from -slot even though a new +slot is queuing and overloading it.  This resulted in the state-machine valid, but confusing behavior that if you +slot before a prior -slot attack finished, then it might consider the weapon to swap back to on the second +slot as the original.  Make this more intuitive by making sure we forward the prior -slot to last-weapon before this.
probably worth improving impulse behavior immediately after this by using queue_slot to eliminate a bunch of cases for these held impulses that can be clobbered.
=> weapons: fix mashing +slot

share/defs.h, ssqc/tforthlp.qc, ssqc/weapons.qc
While internal usage has migrated to `cmd menu`; there's still external use via legacy impulse 5 bind which this hits.  Just bringing it back is simplest.
=> impulses: restore TF_CLASSMENU

csqc/csextradefs.qc, csqc/events.qc
Due to the world being interpolated an additional 1/2 rtt, our prior ping correction was slightly off.
Change the default correction to a full rtt, but also introduce `fo_grentimer_ping_frac` to control the total latency corrected.  A value of `fo_grentimer_ping_frac 0.5` will restore the behavior prior to this change.
=> grentimers: default fo_grentimer 2 to full rtt correction

ssqc/demoman.qc, ssqc/qw.qc
When a demoman dies, his pipebombs detonate.
When a demoman detonates his pipebombs and kills themself...
... their pipebombs... detonate.
You start to see the problem.  Re-entrancy in death handling on self-detpipe would result in nested detpipe call, however, both the parent and child calls are working on the same pipe lists and so subsequent parent execution will result in a duplicate detonation for anything handled by the child.  Resulting in spurious explosions at (0,0,0) when the removed ent is redetonated.
Fix by preventing detpipe nesting; the second case will no longer trigger a second detpipe.
=> weapons: prevent recursive detpipe

csqc/weapon_predict.qc
Restores dynamic light for soldier and pyro rockets. Can be enabled/disabled via `r_rocketlight 0/1`
Appearance (color) can be controlled via `r_rocketlight_color`. [ Note: We ignore the radius specifier that can be embedded into color. ]
=> weapons: add dynamic lights for rockets

csqc/status.qc
The scoreboard was previously trying to print every possible line for every team, this both added overhead and allowed for potential position reuse (since it could examine previously used slots and try to render them).  Fix this by just using the count we already have.
=> scoreboard: bound iteration

csqc/csextradefs.qc
Now that we're rendering the scoreboard, there are potentially many more individual elements going into the cache; bump the capacity in case we're pushing near it.
=> hud render cache: bump size

csqc/weapon_predict.qc, share/defs.h, ssqc/tforthlp.qc, ssqc/weapons.qc
This was a rat's nest of a state machine which required a bunch of unpleasant translation, state tracking, and handling.  Replace with direct invocation of the native slot and weaplast, which gets rid of all special handling of +slot on client and server.
=> impulse: remove legacy QUICKSLOT/QUICKSTOP

csqc/hud_helpers.qc, csqc/input.qc
- Input is no longer passed through when the hud editor is open
- Escape now consistently opens the FO menu, or closes an open menu .. but does not open the system menu (0 from the FO menu does this)
- Escape now properly exits the hud editor (without a save as before, although this is still a little sketch as there are other ways to trigger it, oh well)
=> HUD: fix escape handling and input capture

csqc/csextradefs.qc, csqc/status.qc
Scoreboard fields were being rendered with menu associated colours, which ended up in blending / channels being flattened when combined with coloured names. Fix this and generally make the scoreboard a little easier to read.
=> hud: fix scoreboard colours

csqc/main.qc, csqc/weapon_predict.qc
Currently projectiles and players are interpolated on separate clocks, which can lead to frustrating hit registration.  Introduce support to calculate how much player prediction is occurring, then synchronize projectiles fired by the current client against that.
Not yet enabled by default.  Enabled by including a 2 bit in fo_wpp_beta. Renames/adds two new cvars:
wpp_adv_selfp_ms (extra nudge to add to our own projectiles, up to ping)
wpp_adv_remotep_ms (extra nudge to add to others' projectiles, up to ping)
=> wpp: match projectile prediction to player prediction

csqc/input.qc
We cleaned up a bunch of the input capture code, one escape that was some of the in game menus such as the engineer build menu were now correctly passing through e.g. WASD consistently, however, they weren't consuming the inputs that definitely applied to them.
=> hud: make sure we capture inputs on in game menus

csqc/main.qc
The viewport calculation was only getting updates in input_frames then consumed in rendering, reverse this -- calculate our vectors in rendering and use them in input_frames so that the viewport doesn't get an effective fps drop (rendered remains high, but effective drops with view calc).
=> experimental: improve (fix?) motion blur

csqc/main.qc, csqc/weapon_predict.qc
Beyond being much cleaner in terms of application and reversion, the instant response means that the values aren't pushed to the next input frame resulting in behavior that appears equivalent to server specified maxspeed.
Neither will generate skips from any directional strafing alone.
It's possible in both cases to generate skips (from legitimately going too fast) from the extra acceleration you can generate from viewangles, but you're just legitimately going too fast in both cases, behavior is the same).
=> weapon pred: use input_movevalues instead of cl_forwardspeed et al

csqc/weapon_predict.qc, ssqc/client.qc, ssqc/scout.qc, ssqc/tfort.qc, ssqc/tfortmap.qc, ssqc/weapons.qc
Now that we have so many implementations floating around, all of the state around how we heal, do timers, clear on cap, etc is a giant mess.  Even figuring out what the conc type is requires a multi-way eval.
Refactor all of this so it goes through a few common functions.
All so we can have bubbles on the new conc.  The long form name enable name is also now fixed to be `fo_concuss`.
=> conc: massive cleanup

csqc/weapon_predict.qc, ssqc/tfort.qc
We really don't need to do much with client movespeeds anymore, our maxspeed handling does the work.  Remove some stuffs for legacy clients that could have led to sticky speeds; we now only stuff reasonable (fast) defaults to a spec.
=> mp: remove stuffs

csqc/main.qc, csqc/weapon_predict.qc, share/prediction.qc, ssqc/scout.qc, ssqc/status.qc
- Some Brazilian feedback is that it still felt a little too easy to hit right after conc affect so do some things to make the curve more parameterizable. Particularly, reducing the period of initial rotations (to accelerate how fast aim is moving) for the first few seconds before falling off.
- Slightly increase base amplitude, period is no longer fixed per above
- Remove sync on now redundant period
- Reduce effect for medic by default
- Increase effect for heavy by default
- More run-time tunables to shape the curve a
=> experimental: tune new conc

csqc/hud_helpers.qc
- effective pre-increment was inserting a space on rendered elements
- also just update the threshold equivalent to support use_red markup, even though it's not currently used
=> hud: fix spacing on updated text rendering funcs

ssqc/actions.qc
Looks like Player entered the game and issued a `reloadnext` without a class, crashing server.
```
stagingserver_1  | 2023-05-01T10:04:37.458118664Z Player entered the game
@@ hydr0 building sentry gun @ someplace @@2055Z (@B@.hydr0.bud$.):
stagingserver_1  | 2023-05-01T10:04:40.270545081Z [5] minutes remaining
stagingserver_1  | 2023-05-01T10:04:43.866382217Z zenon played catch with Sakunera's grenade
stagingserver_1  | 2023-05-01T10:04:45.353322825Z NEWBY got too close to his own grenade
stagingserver_1  | 2023-05-01T10:04:54.509534859Z zenon played catch with Sakunera's grenade
stagingserver_1  | 2023-05-01T10:04:55.511904046Z @B@.RedfoX. is mown down by @B@.hydr0.bud$.'s sentry gun
stagingserver_1  | 2023-05-01T10:04:57.391470630Z @B@.wm. played catch with Mortal's grenade …
```
=> Prevent server crashing when reloadnext issued without playerclass

csqc/events.qc, csqc/main.qc
#The current login code is leaking file handles in two places which leads to login failures when we run out of handles and it's unable to read the token.
Fix this but also just refactor so we're not duplicating the read/send path between client and server initiated.  Add instructions for people who dont have a token to visit the FO website to get one.
=> login: fix file-handle leaks and refactor

csqc/main.qc, csqc/weapon_predict.qc, share/weapons.qc
pecan was dependent using bugs in the old +slot implementation so that he could switch between reds/yellows while using a +slot bind.
Add a new client command to do what he really wants:
to be able to swap between reds/yellows, swapping to reds if neither active
We implement a more generic form of this, "slot_a <slot_a> <slot_b>".  This lets you bind it with 2 passed slots, when activated, it will switch to slot_a if neither is selected, otherwise it will alternate between them.
pecan's use case becomes: bind key slot_a 1 2
=> client: add slot_a for alternating slot selection

csqc/main.qc
The first client_alias bind was being swallowed because there was an partially constructed command in the buffer it was being appended to.
=> init: fix missing new line

csqc/weapon_predict.qc
This also needs to be put back where it was, otherwise it breaks `r_drawviewmodel 0` to hide the viewmodel.
=> wp: restore zero check on r_drawviewmodel

csqc/main.qc, csqc/weapon_predict.qc
More quickly update enable state on player/state transitions.  Also no longer wait for stable ping since we're transitioning away from ping toggle.
=> wp: update enable state on player transitions

csqc/weapon_predict.qc
Since we no longer wait for ping to stabilize it's possible to race with receiving the prediction entity from the server; ensure we synchronize on this.
=> wp: make sure that we've received prediction ent (reupload)

csqc/events.qc, ssqc/actions.qc, ssqc/status.qc
Early return when spectator/observer was preventing the last sbar update from being cached, resulting in spectators getting absolutely reamed by messages, in particular ident.  Further improve this by only sending ident updates when there is an actual change, rather than constantly.
This could well explain the proxy overflows we see when spectating.
=> spec: fix ident string spam (maybe fix spectate w/ proxy?)

share/commondefs.qc
Some of these will be reintroduced, but we disabled elsewhere as a bit of hack around ezq issues so clear the mask then reintroduce with removal of that.
=> tfx: clear enable mask

csqc/csextradefs.qc, csqc/events.qc, csqc/weapon_predict.qc
Make grenades more responsive by responding to the prime immediately and starting the grenade timer client-side without waiting for it to come back from the server.  At higher pings, this will result in less of the grenade wav being truncated.
Currently behind `fo_beta_local_grenade` for testing.
=> wp: add support for local grenade priming

share/commondefs.qc, share/physics.qc, share/prediction.qc, ssqc/rewind.qc
The QW protocol is fairly asynchronous in its event ordering; with much being driven off new player packets rather than constant time boundaries.  Try using rewind positions in projectile travel to improve/make registration more consistent.
=> rewind: use rewind positions during physics updates

csqc/events.qc
When spectating an already primed player, off a fresh connect, it's possible to get a throw message with no prime, meaning there's no last grenade timer to set thrown on.
=> spec: handle throw without prime

csqc/main.qc
Refactoring accidentally had this as >= 0
=> wp: fix is_alive to be health>0

csqc/weapon_predict.qc, ssqc/weapons.qc
When queued on attack_finished we leave other impulses like weapon changes on the line until it is finished, making it possible for them to be overwritten when more than one impulse is sent.
Improve this by moving weapon impulses (except quickslot because it's difficult to do the right thing there) to immediately queue rather than stay pending so that we can process them more reliably.
Also add two new client options:
`fo_nofirealpha` (default: -1) when set (e.g. not -1) controls alpha when you
can't fire
`fo_hue_weaponswap` (default: 0) when set, allows you to visually swap weapons
prior to attack finished.
Note that these can be combined.
=> weapons: make weapon changing more reliable and add new features

csqc/main.qc, csqc/weapon_predict.qc, share/prediction.qc, ssqc/client.qc
Clients transition between entities on entering/leaving the game, which allows for weapon prediction to be initialized more than once now that we also use it for spectators.  Free old initializations when this occurs.
Also force aggressve refresh when spectating a new player.
=> wp: free duplicate entities, force refresh on swap

csqc/weapon_predict.qc
Didn't delete old case when moving.
=> wp: fix 'reloading' spam

csqc/csextradefs.qc, csqc/main.qc
The new +slot binds were missing the prior behavior of returning to the last weapon fired when `fo_default_weapon` was not set.  Implement this.  Move stack to 0-index instead of 1-index, simpler and fixes latent overflow bug.
=> client: make -slot swap to prev weap

csqc/main.qc
Sometimes we're seeing zeros sneak in here.
=> client: make sure always return a usable slot

csqc/weapon_predict.qc, share/commondefs.qc, share/prediction.qc, ssqc/client.qc, ssqc/player.qc, ssqc/pyro.qc, ssqc/qw.qc, ssqc/rewind.qc, ssqc/weapons.qc
It's possible to die in between the time that you fire and the server receives you firing.  This is particularly frustrating since you can often see the client side projectile disappear as a result of the server processing your death first.
Handle this by introducing limited reconciliation that can emit projectiles in this window.  Needs more integration with rewind and hitscan but good enough for a first try.
=> antilag: rewind for death projectiles

ssqc/client.qc
When we refactored how the prediction update calculation occurred it could miss elements in think, allowing a handled impulse to propagate to the next frame. This ended up being typically invisible because it wouldn't be an effect-frame, but with very low pings it was possible for this to occur; resulting in effects like some double prints and double projectiles.
=> wp: fix state tear

csqc/events.qc, ssqc/status.qc
- Make sure we only play the timer for the selected player (or none)
- Make sure we obey FL_GT_SOUND when spectating
- Disable broadcast until we re-enable TFX
=> grentimers: misc spec fixes

ssqc/client.qc, ssqc/quadmode.qc, ssqc/qw.qc, ssqc/tfortmap.qc
Add a new localinfo {`drg`, `disable_resup_gren`} that allows disabling pack resupply of grenade1 (controlled by 1-bit) and grenade2 (controlled by 2-bit)
e.g.
`rcon localinfo drg 1` -- disable picking up gren1s
`rcon localinfo drg 3` -- disable picking up gren1s and gren2s
Does not affect backpack grenade pickup.
Automatically enabled (=3) for 2v2 quads.
=> grens: add disable_resup_gren and enable in 2v2

csqc/weapon_predict.qc
If we re-select the weapon we have queued, it should override any queued weapon. This was resulting in quick-fire aliases occasionally generating ghost projectiles.
=> wp: make sure requeueing the current slot clears the queued slot

csqc/csextradefs.qc, csqc/hitfeedback.qc, csqc/main.qc, csqc/pmove.qc, csqc/status.qc, csqc/tfx.qc, csqc/weapon_predict.qc, share/animate.qc, share/classes.qc, share/prediction.qc, ssqc/client.qc
Introduces a full integration for CSQC side movement prediction.  I'd originally intended to break this up into more granular commits but some of the refactoring became too painful.
A lot of the base structure is based on the excellent CSQC reference, but with many bugs and a first pass at refinements.  Does some useful things such as computation caching and error smoothing.
Many things are still missing, including some basics such as correct spectator and probably water movement.
Extremely off by default with no controls to turn it on by default. To toggle for current connection use `fo_beta_pmove 0/1`.
=> pmove: infrastructure and bare implementation

csqc/csextradefs.qc, csqc/pmove.qc, share/prediction.qc
Since we obscure the networked player, effects such as flag glow were not being rendered correctly.  Reproduce these when clientside pmove is used.
=> pmove: render effects locally

csqc/main.qc, csqc/pmove.qc, csqc/weapon_predict.qc, share/commondefs.qc, share/prediction.qc, ssqc/client.qc, ssqc/spect.qc, ssqc/tfort.qc
pmove can now be turned on with a persistent enable: `fo_pmove 0/1`. Also smooth out how much the view bounces around during transitions and prevent races on maxspeed.
=> pmove: add persistent enable

csqc/pmove.qc
Now always enabled with `fo_pmove 1`
=> pm: take self knockback prediction out of beta

csqc/pmove.qc
For example, dont allow conc nudges from previous life the lerp the next.  This is a pretty narrow window but annoying when it does happen with high ping.
=> pmove: add life-associated expiry to nudges

ssqc/client.qc, ssqc/helpers.qc
We depend on discord_channel_id which is not initialized until later.  Just move to end of init.
=> new-balance: move auto-init down

share/commondefs.qc, share/prediction.qc, ssqc/debug.qc, ssqc/rewind.qc
This fixes leaking ents with sky collisions.
=> core: finish removing s_time from server side, fix entity removal

share/defs.h, ssqc/client.qc, ssqc/qw.qc, ssqc/tfortmap.qc, ssqc/weapons.qc
size limits(?) on bitops dont play well with large enumflags values.  Split tfstate into a second word, moving some of our less commonly used fields for now.
This fixes issues like infinite tranq
=> core: split tfstate into pstate

share/animate.qc
Being gibbed does not reset some of the animation state and so weapons which fired in animation were able to continue firing.  Prevent this.
=> weapons: fix firing after dead when gibbed

ssqc/events.qc
haze-stats currently behaves differently wrt over-damage (e.g. more damage than it takes to kill someone) than in-game stats.  The in-game stats only log the damage actually done while haze-stats includes the "over" damage.
Align this by logging true-damage for both.
=> core: make haze-stats align better with in-game stats

ssqc/client.qc
To enable for testing:
`rcon localinfo apcd 1`
=> demoman: disable allpipes_cooldown by default

ssqc/demoman.qc
The cooldown check would allow a pipe thrown as a demoman was dying to survive past death.
=> demoman: fix death bug with new allpipes_cooldown

csqc/pmove.qc
was using if (function_ptr) [always true] instead of calling function
=> pmove: fix maxspeed
